name: Cron Cleanup

on:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches:
      - main
  create:
    branches: 
      - fcron/*
      - fcron
      - fcron*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo
        run: |
          git clone https://${{secrets.GH_WORKER_TOKEN}}@github.com/${{ secrets.GH_WORKER_USER}}/${{ secrets.GH_WORKER_MAIN_REPO}}.git .
          pip install -q -r requirements.txt
      - name: Clean
        run: |
          export $(xargs < .env)
          python cron_cleanup.py