name: Cron Cleanup

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo
        run: |
          git clone https://${{secrets.GH_WORKER_TOKEN}}@github.com/${{ secrets.GH_ORIG_USER}}/${{ secrets.GH_ORIG_REPO}}.git .
          pip install -r requirements.txt
      - name: Clean
        run: |
          export $(xargs < .env)
          python cron_cleanup.py
