name: Worker Run

on:
  create:
    branches: 
      - job/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Current Job Name
        run: echo "${GITHUB_REF#refs/heads/job/}"
      - name: Get Repo
        run: |
          git clone https://${{secrets.GH_ACCESS_TOKEN}}@github.com/${{ secrets.GH_ORIG_NAME}}/${{ secrets.GH_ORIG_REPO}}.git .
      - name: Install OS Libraries
        run: |
          export $(xargs < .env)
          export DEBIAN_FRONTEND=noninteractive
          pip install -r requirements.txt
          sudo wget -qO /usr/share/keyrings/nextdns.gpg https://repo.nextdns.io/nextdns.gpg
          echo "deb [signed-by=/usr/share/keyrings/nextdns.gpg] https://repo.nextdns.io/deb stable main" | sudo tee /etc/apt/sources.list.d/nextdns.list
          sudo apt-get update && sudo apt-get install -y curl python3-dev build-essential ffmpeg apt-transport-https nextdns vlc
          pip install playwright pytest-playwright
          playwright install chromium
          DEBIAN_FRONTEND=noninteractive playwright install-deps
          sudo nextdns install -config ${{ env.NEXTDNS_CONFIG_ID}} -report-client-info -auto-activate
      - name: Run Job
        env:
          DYNO: true
        run: |
          export $(xargs < .env)
          sudo chmod -R 777 /tmp
          mkdir -p /tmp/playwright_storage/videos
          python worker.py ${GITHUB_REF#refs/heads/job/}
          zip -r /tmp/playwright_storage/videos.zip /tmp/playwright_storage/videos