name: Worker Run

on:
  create:
    branches: 
      - job/*

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Print Current Job Name
        run: echo "${GITHUB_REF#refs/heads/job/}"
      - name: Get Repo
        run: |
          sudo chmod -R 777 /tmp
          mkdir -p /tmp/dest_repo_clone
          git clone https://${{ secrets.GH_WORKER_TOKEN}}@github.com/${{ secrets.GH_WORKER_USER}}/${{ secrets.GH_WORKER_MAIN_REPO}}.git /tmp/dest_repo_clone
      - name: Install OS Libraries
        run: |
          export $(xargs < /tmp/dest_repo_clone/.env)
          export DEBIAN_FRONTEND=noninteractive
          pip install -r /tmp/dest_repo_clone/requirements.txt
          sudo wget -qO /usr/share/keyrings/nextdns.gpg https://repo.nextdns.io/nextdns.gpg
          echo "deb [signed-by=/usr/share/keyrings/nextdns.gpg] https://repo.nextdns.io/deb stable main" | sudo tee /etc/apt/sources.list.d/nextdns.list
          sudo apt-get update && sudo apt-get install -y curl python3-dev build-essential ffmpeg apt-transport-https nextdns vlc
          pip install playwright pytest-playwright
          playwright install chromium
          DEBIAN_FRONTEND=noninteractive playwright install-deps
          sudo chmod 777 /etc/hosts
          curl https://raw.githubusercontent.com/nickspaargaren/no-google/master/google-domains >> /etc/hosts
      - name: Run Job
        env:
          DYNO: true
        run: |
          export $(xargs < /tmp/dest_repo_clone/.env)
          sudo nextdns install -config ${{ env.NEXTDNS_CONFIG_ID}} -report-client-info -auto-activate
          sudo nextdns start && sudo nextdns activate
          python /tmp/dest_repo_clone/worker.py ${GITHUB_REF#refs/heads/job/}
      - name: Archive Folder
        if: always()
        run: |
          rm /tmp/dest_repo_clone/.env
          rm /tmp/dest_repo_clone/.env.sample
          find /tmp/dest_repo_clone -mindepth 1 -maxdepth 1 -type d -not -name temp -exec echo rm -rf '{}' \;
          zip -r /tmp/fullpath.zip /tmp/dest_repo_clone
      - name: Archive code coverage results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: videoResults
          path: /tmp/fullpath.zip